webtalk_init -webtalk_dir C:/ProgsData/Data/Labs/HardwareAccelerator/designs/rtl/sigma/syn/syn_5stage/NEXYS4_DDR/NEXYS4_DDR.sim/sim_1/behav/xsim/xsim.dir/riscv_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Dec 15 23:30:49 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "629e7586-fe8b-4b7a-919b-1f02dff79994" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "db908482450846a6b240e55f3ac5423d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i9-13900H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "19524_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4176506004 -regid "" -xml C:/ProgsData/Data/Labs/HardwareAccelerator/designs/rtl/sigma/syn/syn_5stage/NEXYS4_DDR/NEXYS4_DDR.sim/sim_1/behav/xsim/xsim.dir/riscv_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/ProgsData/Data/Labs/HardwareAccelerator/designs/rtl/sigma/syn/syn_5stage/NEXYS4_DDR/NEXYS4_DDR.sim/sim_1/behav/xsim/xsim.dir/riscv_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/ProgsData/Data/Labs/HardwareAccelerator/designs/rtl/sigma/syn/syn_5stage/NEXYS4_DDR/NEXYS4_DDR.sim/sim_1/behav/xsim/xsim.dir/riscv_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
